In [ ]:
import numpy as np
import pandas as pd
import shutil

df = pd.read_csv('ds_dirty_fin_202410041147.csv', delimiter=',',dtype = str)
df

In [ ]:
dfcl = df.dropna(subset = ['source_cd']).copy()
dfcl

In [5]:
dfcl['source_cd'] = dfcl['source_cd'].str.upper()
df_sources = dfcl.groupby(['source_cd']).size().reset_index(name = 'records')
df_sources

  source_cd  records
0      BANK   182455
1     BANK2   347204
2   FITNESS    44405
3       ISP    75146
4    STREAM    87036
5     TELCO   217306
6    TRAVEL    51784

In [7]:
df_sources['columns'] = 0

In [ ]:
sources = list(dfcl.source_cd.unique())

['BANK', 'STREAM', 'TELCO', 'BANK2', 'FITNESS', 'ISP', 'TRAVEL']

In [9]:
for rec in sources:
  df_sources.loc[df_sources['source_cd'] == rec,'columns'] = len(dfcl[dfcl.source_cd == rec].dropna(axis='columns',how='all').columns)

df_columns = list(dfcl.columns)

In [10]:
df_columns.remove('client_id')
df_columns.remove('create_date')
df_columns.remove('update_date')

In [11]:
def trim(str1):
  return str1.replace(' ', '')

In [12]:
dfcl = dfcl.fillna('')
for rec in df_columns:
  dfcl[rec] = dfcl[rec].apply(trim)
  dfcl[rec] = dfcl[rec].str.upper()

In [ ]:
dfcl.drop_duplicates(subset=df_columns, inplace=True)
dfcl

,client_id,client_first_name,client_middle_name,client_last_name,client_fio_full,client_bday,client_bplace,client_cityzen,client_resident_cd,client_gender,...,fin_loan_value,fin_loan_debt,fin_loan_percent,fin_loan_begin_dt,fin_loan_end_dt,stream_favorite_show,stream_duration,create_date,update_date,source_cd
0,596118586,МЕДЖИД,КУЗАРОВИЧ,ЕВДУНОВ,ЕВДУНОВМЕДЖИДКУЗАРОВИЧ,1992-08-23,ДЕР.КИРГИНЦЕВОАРОМАШЕВСКОГОР-НАТЮМЕНСКОЙОБЛ.,RUS,Д,М,...,,,,,,,,2020-07-16 05:10:57.904,2020-07-16 05:10:57.904,BANK
1,747208737,МАНСЫР,ХИРСАНОВИЧ,ПОВОД,ПОВОДМАНСЫРХИРСАНОВИЧ,1987-03-15,,,,М,...,,,,,,STARWARS:ANEWHOPE,1187,2020-11-13 21:33:19.620,2020-11-13 21:33:19.620,STREAM
2,625104053,НУРДИНБЕК,УВАЙСОВИЧ,БУРНАС,БУРНАСНУРДИНБЕКУВАЙСОВИЧ,1961-04-05,СЕЛОДИОРОВАТЯЧЕВСКОГОРАЙОНАЗАКАРПАТСКОЙОБЛАСТИ,RUS,,М,...,,,,,,,,2022-09-06 20:41:55.362,2022-09-06 20:41:55.362,TELCO
3,624196811,АФАЯТ,ГОРДИЕВНА,БОНДАЖЕВСКАЯ,БОНДАЖЕВСКАЯАФАЯТГОРДИЕВНА,1976-06-01,,,,Ж,...,,,,,,ОСТАТЬСЯВЖИВЫХ,35,2021-08-17 19:00:45.024,2021-08-17 19:00:45.024,STREAM
4,177500487,САХИЯ,ФИДАЕВНА,РАЗУЕВА,РАЗУЕВАСАХИЯФИДАЕВНА,1961-07-31,,,,Ж,...,,,,,,НАЧАЛО,834,2022-11-05 05:37:58.131,2022-12-04 00:00:09.068,STREAM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005525,341669039,МЕЙРАМ,АВХАДИЕВИЧ,МАРКЕЕВИЧ,МАРКЕЕВИЧМЕЙРАМАВХАДИЕВИЧ,1939-07-14,,,,М,...,,,,,,КРЕСТНЫЙОТЕЦ2,926,2021-12-22 20:40:33.787,2021-12-22 20:40:33.787,STREAM
1005526,790628473,БАГЖАТ,САНЖАСАМСОНОВНА,МАЗОВА,МАЗОВАБАГЖАТСАНЖАСАМСОНОВНА,1994-10-24,,,,Ж,...,,,,,,РИКИМОРТИ,1198,2023-09-08 08:40:55.500,2023-09-08 08:40:55.500,STREAM
1005527,978076125,ДИНАИДА,КАЗИМИРОВНА,БУБНЕВА,БУБНЕВАДИНАИДАКАЗИМИРОВНА,1995-09-03,,,,Ж,...,,,,,,МАТРИЦА,39,2022-10-01 18:33:55.676,2022-10-01 18:33:55.676,STREAM
1005528,224784654,НЕНИЛА,УУДОВНА,ЖУЖУК,ЖУЖУКНЕНИЛАУУДОВНА,1979-01-02,,,,Ж,...,,,,,,ПОБЕГ,214,2021-06-02 05:44:56.775,2021-11-05 15:04:17.259,STREAM
1005529,738145160,НАЗАНИ,ЯХИЕВНА,БЕЗЮК,БЕЗЮКНАЗАНИЯХИЕВНА,0062-07-26,,,,Ж,...,,,,,,СЕМЬ,1403,2023-03-08 01:02:52.245,2023-03-08 01:02:52.245,STREAM

In [14]:
conditions = list()
choices = list(range(len(sources)))

In [15]:
for rec in choices:
  conditions.append(dfcl['source_cd'] == sources[rec])

In [16]:
dfcl['source_id'] = np.select(conditions, choices)

In [ ]:
df_sorted = dfcl.sort_values(by = ['source_id','client_inn'])
df_sorted

In [18]:
dfcl_inn = dfcl.groupby(['client_inn']).filter(lambda g: len(g) > 1).groupby(['client_inn']).size().sort_values(ascending = False)

In [ ]:
dfcl.loc[dfcl['client_inn'] == '593147430785'].sort_values(by = ['source_id','update_date'], ascending = [True,False])